export const  CHANGE_NAV='header/CHANGE_NAV';

export const  CHANGE_EXERCISEIMPLEMENT='header/CHANGE_EXERCISEIMPLEMENT';

export const  CHANGE_EXERCISEFIXEDIMPLEMENT='header/CHANGE_EXERCISEFIXEDIMPLEMENT';

export const  CHANGE_EXERCISEFREEIMPLEMENT='header/CHANGE_EXERCISEFREEIMPLEMENT';

export const  CHANGE_EXERCISEBODY='header/CHANGE_EXERCISEBODY';

export const  CHANGE_EXERCISEDIFFICULT='header/CHANGE_EXERCISEDIFFICULT';

export const  CHANGE_PLANAIM='header/CHANGE_PLANAIM';

export const  CHANGE_PLANDAYS='header/CHANGE_PLANDAYS';

export const  CHANGE_PLANIMPLEMENT='header/CHANGE_PLANIMPLEMENT';

export const  CHANGE_PLANBODY='header/CHANGE_PLANBODY';

export const   UPDATE_EX_SELECTIMPLEMENT='header/UPDATE_EX_SELECTIMPLEMENT';
