export const GET_FOOD_SORT_DATA = "food/GET_FOOD_SORT_DATA"
export const GET_FOOD_DATA = "food/GET_FOOD_DATA"
export const GET_FOOD_DETAIL = "food/GET_FOOD_DETAIL"
export const GET_RELATED_FOOD = "food/GET_RELATED_FOOD"
export const GET_SEARCH_FOOD = "food/GET_SEARCH_FOOD"
