export const CHANGE_IMPLEMENT_DATA='implement/CHANGE_IMPLEMENT_DATA'

export const GET_IMPLEMENT_DETAIL='implement/GET_IMPLEMENT_DETAIL'

export const UPDATE_BMI_RESULT='implement/UPDATE_BMI_RESULT'

export const UPDATE_DRINK_RESULT='implement/UPDATE_DRINK_RESULT'

// export const UPDATE_DRINK_RESULT='implement/UPDATE_DRINK_RESULT'
//标准体重
export const UPDATE_STANDARD_RESULT='implement/UPDATE_STANDARD_RESULT'
// 燃脂心率
export const UPDATE_HEARTRATE_RESULT='implement/UPDATE_HEARTRATE_RESULT'

export const UPDATE_WATER_RESULT='implement/UPDATE_WATER_RESULT'

